### PR TITLE
Fix: list-tracked in subdir would print invalid paths

### LINKED ISSUE #230: list-tracked outputs invalid paths

### PR DESCRIPTION
**Pull request by rhopfer**
Fixes #230

### CODE REVIEW

**Comment by RichiH** [comment]
I suspect I should have a look at all other ls-files, as well. I dimly remember not being able to fix an issue with gitignores...

**Comment by RichiH** [comment]
(That does not mean I would stop merging your PRs, mind)

**Comment by danielshahaf** [comment]
> I suspect I should have a look at all other ls-files, as well. I dimly remember not being able to fix an issue with gitignores...

The other callsites of `ls-files` all do either `cd "$VCSH_BASE"` or `export GIT_DIR`, so should be okay.  (Okay for now, I mean; a future patch might accidentally break this.)

**Comment by RichiH** [comment]
Do you see any hurt in just doing it in all the places? I can't think of any.

**Comment by danielshahaf** [comment]
> Do you see any hurt in just doing it in all the places? I can't think of any.

On the contrary: I think that changes to improve the code's robustness --- e.g., to ensure that GIT_DIR is always set --- are the way forward.

I also wonder what could be done to ensure that _future_ subcommands don't make this mistake.  For example, perhaps there should be a run_git() { env GIT_DIR=... git "$@" } helper function?

**Comment by danielshahaf** [comment]
Speaking of robustness: delete_files() uses 'echo "$file"' which isn't well-defined when $file starts with a minus or contains a backslash.

**Pull request merged**
