### PR TITLE
Make remote branch finding more robust

### PR DESCRIPTION
**Pull request by RichiH**
Fixes: https://github.com/RichiH/vcsh/issues/294

This patch does three things at once:

1. Default to trying `main` first
2. Walk through several remote branches, in order
3. Test remote branches a lot earlier than before, aborting earlier

Signed-off-by: Richard Hartmann <richih@richih.org>

### CODE REVIEW

**Review by alerque — CHANGES_REQUESTED** [review]
I don't think this is the best approach at all, we shouldn't care at all what branches are setup and iterating over a hard coded list is worse than the previous fallback to one hard coded option. In my case it will fail more often that the current because I have `development` branches that are **not my default branch**.

Why do we need to know this at all? For `init()` the user's Git config should take care of setting a default. For `clone()` doing a clone already does the right thing and pulls the default remote branch even if it's named *fooBarBazBob*. The only place we were using a branch name too early is in checking if the repository is empty, and we can do that with `git ls-remote "$VCSH_REMOTE" HEAD` instead of a branch name. We don't even need to parse the answer, just knowing there is a HEAD is enough and we can go ahead with the close using no branch name at all.

**Comment by RichiH** [comment]
The current code does not work with `vcsh clone` and remote `main` branch which is what GitHub uses as default for new repos; ran into that migrating some repos with broken remotes over to GH.

I went off the list of branch names Git suggests; we could drop `development` as it's kinda stupid as the _default_ anyway.

But something I didn't consider: `git ls-remote "$VCSH_REMOTE" HEAD` and then simply `git clone`. I know that didn't work a decade ago which is why `clone()` is building a clone step-by-step, but maybe that changed. Assuming that works: I would be fine dropping the old code completely or moving it into a `clone_legacy()` in case someone has an ancient system they want to play with.

**Comment by alerque** [comment]
I've never heard of (or at least don't remember) any Git server that couldn't handle `git clone <address>` without any branch information. I suspect the issue here is not that `git clone` won't work that way, it's that we aren't using `git clone` at all: the current clone function does our own init (including hooks), then uses `git fetch`. The right thing to do here is probably to figure out how to decouple that. I wouldn't realy expect `pre/post-init` hooks to run on `vcsh clone` for example.

**Comment by RichiH** [comment]
The problem was (is?) that `WORKTREE` and such were not honored during clone; which forced me to clone by hand. As vcsh kicked off a bit of a buzz in Git circles back then, a lot of work was done around WORKTREE shortly after. I will try if setting WORKTREE before cloning does the right thing, these days.

**Comment by RichiH** [comment]
More testing, trying to figure out what forced me to do it by hand back then:

````
Initialized empty Git repository in /home/richih/.config/vcsh/repo.d/git.git/
vcsh: info: remote branch 'main' found
Switched to a new branch 'main'
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (15/15), done.
Unpacking objects: 100% (24/24), 2.57 KiB | 262.00 KiB/s, done.
remote: Total 24 (delta 3), reused 24 (delta 3), pack-reused 0
From github.com:RichiH/gitrc
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
error: Untracked working tree file '.gitconfig' would be overwritten by merge.
vcsh: fatal: will stop after fetching and not try to merge!
  Once this situation has been resolved, run 'vcsh git pull' to finish cloning.
````

We can't assume that the local `$HOME` is clean from cloned files and need to give useful warnings/errors as `git` is not built to anticipate this.

**Comment by alerque** [comment]
Wouldn't that be better as bare clone first, then checkout the working tree later?

**Comment by RichiH** [comment]
I can certainly try; spent today on unbreaking Debian packaging, and polishing up metamonger. Might take me until the weekend to get time to test it, but will do.

**Comment by alerque** [comment]
Given that we want to see this make the v2 cut, I just handled the merge conflicts and added another tidbit I missed before: that `wc` is a dependency. Otherwise I haven't addressed the issues raised in comments here yet but I'll try to look into it too.

**Review by alerque — CHANGES_REQUESTED** [review]
In reviewing the branch handling (and deciding to maybe not set `$VCSH_BRANCH` at all if the user didn't request it, I notices that L341 is using this variable inside `push()` and `pull()` subcommands, but the only place we're even setting it is in `clone()` subcommands. Something is wrong here.

**Comment by RichiH** [comment]
It's coming in through https://github.com/RichiH/vcsh/pull/253 and it breaks both push and pull. Sorry, I should have caught this during PR review.

https://github.com/RichiH/vcsh/pull/253 to fix.

**Review by alerque — APPROVED** [review]
With #302 taking care of the other problem the rest of this looks good. Not perfect because it doesn't actually do remote default branch discovery, but since I can't figure out a way to do that yet this is definitely better than not having any remote branch latitude at all.

**Pull request merged**
