### PR TITLE
Switch testing from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by alerque**
This is the follow up to #277 after I embarrassing pushed to the wrong repo and hence killed off the PR.

This time the PR is coming from my fork and you can [see the tests in action here](https://github.com/alerque/vcsh/actions/workflows/test.yml?query=branch%3Agh-actions) even though the canonical repository won't run them until the workflow file exists in the default branch.

### CODE REVIEW

**Comment by RichiH** [comment]
Tsk, killing cows...

Your GPG key needs a lifetime extension & push to keyservers, it seems.

**Review by RichiH — APPROVED** [review]

**Comment by alerque** [comment]
Eh? Last I checked it wasn't 2022 yet. Then again the way the world is going I might have missed something. I'll look into why GitHub thinks I'm some unverified scammer.

**Comment by alerque** [comment]
I just looked at half a dozen public key servers and my public key artifacts aren't expired on any of them. I don't know what GitHub is referencing, but I don't think it matters for this PR.

**Comment by alerque** [comment]
@RichiH I finally figured out why GitHub was so grumpy about my GPG signatures. It wasn't that the key in my profile wasn't current –it was– but I had added a subkey since adding the public key to my profile. Their UI also has no support for updating public keys, but deleting and re-adding the public key convinced them the subkeys were all copacetic.

**Pull request merged**
