### PR TITLE
Agnostic

### PR DESCRIPTION
**Pull request by andschwa**
As per PR #114, this adds the `vcsh setup` and `vcsh where` commands, with necessary documentation. It also enables the sourcing of `./.config/vcsh/config`, which `vcsh setup` will automatically create with the `$VCSH_BASE` and `$XDG_CONFIG_HOME` variables set to `$(pwd)` and `$(pwd)/.config` respectively, thus enable "agnostic" use of `vcsh` from the folders with the a `./.config/vcsh/config` file.

It's a work in progress, and probably needs more testing, but I think it's a good way to go about doing this.

### CODE REVIEW

**Comment by andschwa** [comment]
@RichiH What are your thoughts on decentralizing the whole thing? In the end I think it would come out much neater.

**Comment by bertenvdb** [comment]
Anyone still working on this? I would love to be able to track /etc files!

**Comment by andschwa** [comment]
@bertenvdb IIRC it's working, just not merged, give it a try and let me know!

**Comment by bertenvdb** [comment]
@andschwa 
It isn't working for me, but I got the feeling I'm doing something wrong (using version 1.20141026).

I can track ~/ just fine, but any command (such as `vcsh setup testrepo`) I execute in /etc gives me the same output as `vcsh -help`
Except for https://github.com/andschwa/vcsh/commit/15d31a634a3d7a6bff6e3b303d8b062d8bff20d1, I can't find any helpul documentation on `setup` or `base`; not online, not in the man pages, not with `vcsh -help`. `vcsh-help` doesn't even mention `setup` or `base`. 

Is there anything I'm missing? BTW, if it isn't obvious, I'm pretty new to git(hub).

**Comment by andschwa** [comment]
@bertenvdb were you able to apply this patch and use the agnostic features? Just curious.

**Comment by andschwa** [comment]
If ya'll want to take this ever, feel free, but I am clearly never getting back to it 🤣

**Comment by alerque** [comment]
I'm re-opening this PR as #283 because I think the work deserves further review. At least until we decide on some resolution to #100 (whether that is rejecting the feature or implementing something) this seems like at least one reasonable approach. @andschwa no worries at all if you aren't interested in being involved in that process, feel free to unsubscribe from notifications to this PR and anything else that generates noise in your notifications.

**Comment by andschwa** [comment]
It'd be awesome if it ever gets merged, good luck @alerque!

**Pull request closed without merging**
