### PR TITLE
Update INSTALL.md - fixes #152

### LINKED ISSUE #152: Unable to install vcsh after downloading the git repo.
I followed the prerequisites stated [here](https://github.com/RichiH/vcsh/blob/master/doc/INSTALL.md) and even tried this after installing `ruby-ronn`.

This is what I did: 

```
$ git clone https://github.com/RichiH/vcsh
Cloning into 'vcsh'...
remote: Counting objects: 2551, done.
remote: Total 2551 (delta 0), reused 0 (delta 0), pack-reused 2551
Receiving objects: 100% (2551/2551), 586.67 KiB | 514.00 KiB/s, done.
Resolving deltas: 100% (1377/1377), done.
Checking connectivity... done.
```

then, `cd vcsh/`

```
$ sudo make install
[sudo] password for me: 
t/000-tear-env.t ... Can't locate Shell/Command.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at t/000-tear-env.t line 6.
BEGIN failed--compilation aborted at t/000-tear-env.t line 6.
t/000-tear-env.t ... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/001-setup-env.t .. Can't locate Test/Most.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at t/001-setup-env.t line 6.
BEGIN failed--compilation aborted at t/001-setup-env.t line 6.
t/001-setup-env.t .. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/100-init.t ....... Can't locate Test/Most.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at t/100-init.t line 7.
BEGIN failed--compilation aborted at t/100-init.t line 7.
t/100-init.t ....... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/300-add.t ........ Can't locate Shell/Command.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at t/300-add.t line 8.
BEGIN failed--compilation aborted at t/300-add.t line 8.
t/300-add.t ........ Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/950-delete.t ..... Can't locate Test/Most.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at t/950-delete.t line 7.
BEGIN failed--compilation aborted at t/950-delete.t line 7.
t/950-delete.t ..... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/999-tear-env.t ... Can't locate Shell/Command.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at t/999-tear-env.t line 6.
BEGIN failed--compilation aborted at t/999-tear-env.t line 6.
t/999-tear-env.t ... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 

Test Summary Report
-------------------
t/000-tear-env.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/001-setup-env.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/100-init.t     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/300-add.t      (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/950-delete.t   (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/999-tear-env.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=6, Tests=0,  1 wallclock secs ( 0.03 usr  0.01 sys +  0.01 cusr  0.01 csys =  0.06 CPU)
Result: FAIL
make: *** [test] Error 1
```

```
$ perl --version

This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
(with 57 registered patches, see perl -V for more detail)

Copyright 1987-2011, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

### PR DESCRIPTION
**Pull request by absorber**
Added documentation about perl dependencies to reflect this issue - https://github.com/RichiH/vcsh/issues/152

### CODE REVIEW

**Comment by ncanceill** [comment]
Excellent, now I can send a PR to your own branch with my own small changes to what you changed.

**Comment by ncanceill** [comment]
Oh, one last thing, when I asked you to add _"fixes"_ to the PR description, I was not talking about the PR title, but the description text (your [first comment](https://github.com/RichiH/vcsh/pull/155#issue-67592971)).

**Comment by RichiH** [comment]
Can you rewrite this to state that you only need `ronn` in `master`, not `release`?

https://github.com/RichiH/vcsh/pull/167 should also make `prove` opportunistic.

I can easily rewrite it myself, but I guess you want the honour of the patch :)

**Comment by alerque** [comment]
@RichiH This was another of the automatic GitHub closures, it looks like the same reason applies (upstream fork removed). I would re-submit it, but I think this one is obsolete. The things it adds are no longer required for install, only for test, and that is properly document later in the file.

**Pull request closed without merging**
