### PR TITLE
Fix some issues reported by lintian

### PR DESCRIPTION
**Pull request by debian-janitor**
Fix some issues reported by lintian
* Use secure copyright file specification URI. ([insecure-copyright-format-uri](https://lintian.debian.org/tags/insecure-copyright-format-uri.html))
* Bump debhelper from deprecated 7 to 12. ([package-uses-deprecated-debhelper-compat-version](https://lintian.debian.org/tags/package-uses-deprecated-debhelper-compat-version.html))
* Set debhelper-compat version in Build-Depends. ([uses-debhelper-compat-file](https://lintian.debian.org/tags/uses-debhelper-compat-file.html))
* Set upstream metadata fields: Bug-Database, Bug-Submit, Repository, Repository-Browse. ([upstream-metadata-file-is-missing](https://lintian.debian.org/tags/upstream-metadata-file-is-missing.html), [upstream-metadata-missing-bug-tracking](https://lintian.debian.org/tags/upstream-metadata-missing-bug-tracking.html), [upstream-metadata-missing-repository](https://lintian.debian.org/tags/upstream-metadata-missing-repository.html))
* Use secure URI in Vcs control header Vcs-Git. ([vcs-field-uses-insecure-uri](https://lintian.debian.org/tags/vcs-field-uses-insecure-uri.html))

This merge proposal was created automatically by the [Janitor bot](https://janitor.debian.net/lintian-fixes).
For more information, including instructions on how to disable
these merge proposals, see https://janitor.debian.net/lintian-fixes.

You can follow up to this merge proposal as you normally would.

The bot will automatically update the merge proposal to resolve merge conflicts
or close the merge proposal when all changes are applied through other means
(e.g. cherry-picks). Updates may take several hours to propagate.

Build and test logs for this branch can be found at
https://janitor.debian.net/lintian-fixes/pkg/vcsh/fd7f55b5-8e7d-4c62-b2f3-cd780dd96c37.

These changes have no impact on the [binary debdiff](
https://janitor.debian.net/api/run/fd7f55b5-8e7d-4c62-b2f3-cd780dd96c37/debdiff?filter_boring=1).

You can also view the [diffoscope diff](https://janitor.debian.net/api/run/fd7f55b5-8e7d-4c62-b2f3-cd780dd96c37/diffoscope?filter_boring=1) ([unfiltered](https://janitor.debian.net/api/run/fd7f55b5-8e7d-4c62-b2f3-cd780dd96c37/diffoscope)).

### CODE REVIEW

**Review by alerque — APPROVED** [review]

**Comment by alerque** [comment]
RichiH I'm going to leave this one alone for the moment. I need to get my head around how packaging is being handled. I hate the way Debian expects packaging info to be upstreamed, although I think it can also be setup so the packaging data is in a completely separate repository and tracked separately (as most distros do). On the other hand these lint fixes look good to me, so I don't know of any reason not to put them in the `debian` branch and work from there.

**Comment by jelmer** [comment]
FWIW It's common to have the Debian packaging in a separate repository or branch; having it in the upstream branch is unusual and has several downsides.

**Comment by RichiH** [comment]
This PR is against the `debian` branch, where the packaging info lives.

**Comment by RichiH** [comment]
The only reason why it's in the upstream repo is because I am the maintainer of the package, so https://github.com/RichiH/vcsh/tree/debian is the natural place for this branch.

**Pull request merged**
