### PR TITLE
Fix tests under git-2.2

### PR DESCRIPTION
**Pull request by dottedmag**
I have noticed that one of the tests failed under git-2.2

### CODE REVIEW

**Comment by RichiH** [comment]
Could you try to make this dependent on version? I.e. with legacy Git, test for it, with 2.2 you don't?

**Comment by dottedmag** [comment]
It's been deprecated since 2008, maybe it's easier to just drop it? https://github.com/git/git/commit/1dd1239aa33ddd7f159cd183338ef6f71298e29a

**Comment by jwhitley** [comment]
+1 on accepting this PR as-is.

I'm on git 2.4.5, and just got hit by this while trying to install and test the `feature/foreach` branch.

vcsh (rightly) doesn't directly depend on the actual presence or absence of this directory, only on git's external behavior.  The whole `t/100-init.t` suite only has meaning as a collective because each test is fingerprinting the implementation details of git's repo structure.  Moreover, I can't imagine a case where `vcsh init` causes an (old, < v2.2) version of git to pass this suite *except* for `ok -d 'branches';`.

**Comment by RichiH** [comment]
Thanks :)

**Pull request merged**
