### PR TITLE
Completion: Fix the brain split (#270)

### PR DESCRIPTION
**Pull request by danielshahaf**
See #270 and the log messages for details.

@okapia FYI

### CODE REVIEW

**Review by alerque — COMMENTED** [review]
Thanks for taking the time to contribute this @danielshahaf. Are you still using it yourself it this form? I'd like to test it myself before merging and am wondering if you have some test cases I could use each way to see what the effects are.

**Comment by okapia** [comment]
@danielshahaf tagged me on this - I'm a zsh developer but not a vcsh user. From a read of the changed files I can fairly easily vouch for the fact that this looks clearly correct if that gives you some confidence in it. Not knowing vcsh, I can't really help on examples of differences. The change to return status makes it conform to a very common idiom where any function returning 0 should result in the function itself returning 0. This may need a non-trivial zsh configuration to demonstrate. If you use _approximate, you may get approximate completion happening when non-approximate completions were added by one called function but a subsequent one added nothing. This may only occur given suitably contrived matches so could be hard to reproduce but it defintely happens. The use of _call_program is good practice in general wherever completion functions call an external command to generate matches.

**Comment by alerque** [comment]
Thanks for contributing to the review @okapia, those comments were helpful

**Review by alerque — APPROVED** [review]

**Comment by danielshahaf** [comment]
Thanks, @okapia!

**Pull request merged**
