### PR TITLE
Make path to .gitignore.d and .gitattributes.d configurable

### PR DESCRIPTION
**Pull request by miramir**
Fix issue #180

### CODE REVIEW

**Comment by kwbr** [comment]
Any chance to release a new vcsh with this patch applied?

**Comment by alerque** [comment]
Hey @RichiH any chance I could get the short version on the reasoning behind this PR closure?

**Comment by alerque** [comment]
I might have found it, [your comment here](https://github.com/RichiH/vcsh/issues/16#issuecomment-3252116) explains what you were probably thinking. Since it's kind of off topic there maybe humor me for a minute here, but I'm not convinced the logic is correct:

> Users may have $XDG_CONFIG_HOME set to different locations on different machines or several users may use one repo. vcsh could not handle this without softlinks or other hacks. Thus, $VCSH_BASE/.gitignore.d is the only place that makes sense. I could make this a config option, but I doubt this is useful and only serves for people to shoot their own feet.

Of course `$XDG_CONFIG_HOME` may vary from machine to machine, but if it does wouldn't using that variable in our default config by definition solve that? And if the user chooses to override that as a default location, wouldn't the fact that the config is stored in the git repo meta data solve this anyway? If `vcsh` finds the repo at all it would by definition find the related ignores and attributes no matter where they were configured to go, no?

**Comment by RichiH** [comment]
This seems to a side effect of the rename from master to main; and it took me some time figure out that the hint was in the mouse-over of the disabled re-open button... Weird

image

**Comment by RichiH** [comment]
OK, https://github.com/miramir/vcsh is deleted and it seems that verification was triggered by the rename. But, given how GitHub stores forks as one repo in the background, https://github.com/RichiH/vcsh/pull/203/commits/e4addc805b9f05eeaa4187da16ef5742be38d911 still exists

**Comment by RichiH** [comment]
I will report this as a bug to GitHub support.

**Comment by RichiH** [comment]
@alerque: I don't get email for my own "closing" of PRs and issues. Did you get any other close emails at around the same time? If yes, we need to review them all.

**Comment by alerque** [comment]
Yes. There were 4 of them as I recall. Since *most* of them automatically reparented and just those 4 closed I thought at first they were ones you had just decided to ditch—although the lack of comments made me wonder. I didn't notice anything unique about the 4 but now that you point it out I didn't review the status of the downstream forks. I'll track down the other 3.

**Pull request closed without merging**
